[settings]
dotfiles.root = "~/.dotfiles/src"
experimental = true

[env]
MISE_AQUA_REGISTRIES = "file://{{env.HOME}}/.dotfiles/src/.config/mise/aqua-registry.yaml"

[tools]
gh = "latest"
"github:zsh-users/antigen" = "latest"
lazygit = "latest"
neovim = "latest"
ni = "latest"
node = "latest"
starship = "latest"

[dotfiles]
"~/.gitconfig" = {}
"~/.gitignore_global" = {}
"~/.zshrc" = {}
"~/.config/ghostty/config" = {}
"~/.config/nvim" = {}
"~/.config/mise/config.toml" = {}
"~/.zprofile" = {}